### ISSUE TITLE
Blank pages after moved to new server

### ISSUE THREAD

**Issue by kokotko1337** [giterlizzi/dokuwiki-plugin-datatables#47]
**Issue**: After migration datatables showing blank pages

Problem: moved dokuwiki to another server - moved with RSYNC - same rights and ownership.
Everything working, all plugins only Datatables not.

I tried NOCACHE, and touch but without any success.

Do you have idea what it could be ? 

when i delete <datatables> and </datatables> table will be shown.

Example of blank page:
<datatables>
^ Column A ^ Column B ^ Column C ^
| Row A1   | Row B1   | Row C1   |
| Row A2   | Row B2   | Row C2   |
| Row A2   | Row B2   | Row C3   |
</datatables>

Example of page which is shown without any issues:

^ Column A ^ Column B ^ Column C ^
| Row A1   | Row B1   | Row C1   |
| Row A2   | Row B2   | Row C2   |
| Row A2   | Row B2   | Row C3   |

**Comment by giterlizzi** [comment]
You can see errors in Browser JSConsole or in Apache errore logs?

**Comment by POpus** [comment]
I'm having the same problem except I just added datatables to a new server. If i refresh the page with no <datatables> tag it works normally and no JSConsole error is generated. With the tag the attached error is generated and the table looks the same without headers.

[172.25.217.96-1582838729556.log](https://github.com/giterlizzi/dokuwiki-plugin-datatables/files/4264133/172.25.217.96-1582838729556.log)

**Comment by POpus** [comment]
Note. The README.md file in the plugin directory says to install the plugin manually in **/lib/plugins/icons** instead of **/lib/plugin/datatables**

**Comment by liszca** [comment]
In the Firefox console I don't find any errors, but nginx error log:

```
2020/03/12 14:43:51 [error] 207#207: *1243 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/dokuwiki/lib/plugins/datatables/syntax.php:55
Stack trace:
#0 /var/www/dokuwiki/inc/parser/renderer.php(111): syntax_plugin_datatables->render('xhtml', Object(Doku_Renderer_xhtml), Array)
#1 /var/www/dokuwiki/inc/parserutils.php(654): Doku_Renderer->plugin('datatables', Array, 1, '<datatables aut...')
#2 /var/www/dokuwiki/inc/parserutils.php(130): p_render('xhtml', Array, NULL)
#3 /var/www/dokuwiki/inc/parserutils.php(83): p_cached_output('/var/www/dokuwi...', 'xhtml', 'produktion')
#4 /var/www/dokuwiki/inc/html.php(293): p_wiki_xhtml('produktion', 0, true, '')
#5 /var/www/dokuwiki/inc/Action/Show.php(33): html_show()
#6 /var/www/dokuwiki/inc/template.php(98): dokuwiki\Action\Show->tplContent()
#7 /var/www/dokuwiki/inc/events.php(111): tpl_content_core('show')
#8 /var/www/dokuwiki/inc/events.php(256): Doku_Event->trigger('tpl_content_cor...', true)
#9 /var/www/dokuwiki/inc/template.php(83)" while reading upstream, client: 192.168.0.5, server: , request: "GET /doku.php?id=produktion HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "dokuwiki.local:9080", referrer: "https://doku.example.com/doku.php?id=produktion&do=edit"
```

**Comment by giterlizzi** [comment]
@liszca 
Seems you don't have PHP XML module on your server.
Install via package manager, eg.`yum install php-xml` and restart the webserver.

**Comment by giterlizzi** [comment]
@POpus Oops....! Sorry!
